const products =[
  {
    id: 11203290,
    title_fa: "فرز انگشتی مینیاتوری جاب مدل JB-280 مجموعه 280 عددی",
    title_en: "",
    url: {
      uri: "/product/dkp-11203290/فرز-انگشتی-مینیاتوری-جاب-مدل-jb-280-مجموعه-280-عددی",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "جاب",
      category: "[TC,ابزار برقی]",
      metric6: 20,
      dimension2: 47,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 4.4,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سنباده زنی، رنده و پولیش",
      item_category5: "فرز و سنگ رومیزی",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/4b1ee1c6ae6111f37fb61c72a667f1c8435c4630_1682840689.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/4b1ee1c6ae6111f37fb61c72a667f1c8435c4630_1682840689.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 88,
      count: 20,
    },
    default_variant: {
      id: 39781900,
      lead_time: 1,
      rank: 99.88,
      rate: 88,
      statistics: {
        totally_satisfied: {
          rate_count: 11,
          rate: 55,
        },
        satisfied: {
          rate_count: 7,
          rate: 35,
        },
        neutral: {
          rate_count: 1,
          rate: 5,
        },
        dissatisfied: {
          rate_count: 1,
          rate: 5,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 20,
        total_rate: 88,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 63337,
        title: "کمپکس",
        code: "9NYRH",
        url: "https://www.digikala.com/seller/9NYRH/",
        rating: {
          total_rate: 78,
          total_count: 9420,
          commitment: 99.9,
          no_return: 99.2,
          on_time_shipping: 95.2,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.45,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "5 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 19900000,
        rrp_price: 37900000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 47,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 19800000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 12537885,
    title_fa: "مجموعه 35 عددی دریل پیچ گوشتی شارژی جاب مدل JBE-3600",
    title_en: "",
    url: {
      uri: "/product/dkp-12537885/مجموعه-35-عددی-دریل-پیچ-گوشتی-شارژی-جاب-مدل-jbe-3600",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "جاب",
      category: "[TC,ابزار برقی]",
      metric6: 3,
      dimension2: 45,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 4.7,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سوراخکاری و پیچاندن",
      item_category5: "دریل",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/7910d6578029efd17e0e079d78945b5cbbef6858_1693397349.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/7910d6578029efd17e0e079d78945b5cbbef6858_1693397349.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 94,
      count: 3,
    },
    default_variant: {
      id: 43340283,
      lead_time: 1,
      rank: 99.93,
      rate: 93.4,
      statistics: {
        totally_satisfied: {
          rate_count: 2,
          rate: 66.67,
        },
        satisfied: {
          rate_count: 1,
          rate: 33.33,
        },
        neutral: {
          rate_count: 0,
          rate: 0,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 3,
        total_rate: 93.4,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 63337,
        title: "کمپکس",
        code: "9NYRH",
        url: "https://www.digikala.com/seller/9NYRH/",
        rating: {
          total_rate: 78,
          total_count: 9391,
          commitment: 99.9,
          no_return: 99.2,
          on_time_shipping: 95.2,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.45,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "5 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 20990000,
        rrp_price: 38000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 45,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 20980000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 9604654,
    title_fa: "اره زنجیری شارژی کبالت مدل 2700SPM",
    title_en: "",
    url: {
      uri: "/product/dkp-9604654/اره-زنجیری-شارژی-کبالت-مدل-شاخه-بر",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,لوازم و ابزار باغبانی]",
      metric6: 14,
      dimension2: 39,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 3.5,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار برش و تراشکاری",
      item_category5: "اره زنجیری",
    },
    product_type: "product",
    digiplus: {
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/9be8d0ea247cc84c55fe70fd1a138b06a989d382_1665163498.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/9be8d0ea247cc84c55fe70fd1a138b06a989d382_1665163498.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 70,
      count: 14,
    },
    default_variant: {
      id: 34444444,
      lead_time: 1,
      rank: 99.7,
      rate: 70,
      statistics: {
        totally_satisfied: {
          rate_count: 4,
          rate: 28.57,
        },
        satisfied: {
          rate_count: 5,
          rate: 35.71,
        },
        neutral: {
          rate_count: 1,
          rate: 7.14,
        },
        dissatisfied: {
          rate_count: 2,
          rate: 14.29,
        },
        totally_dissatisfied: {
          rate_count: 2,
          rate: 14.29,
        },
        total_count: 14,
        total_rate: 70,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: true,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 272,
        title_fa: "گارانتی اصالت و سلامت فیزیکی کالا",
        title_en: "گارانتی اصالت و سلامت فیزیکی کالا",
      },
      seller: {
        id: 388896,
        title: "کامودیتی",
        code: "CGAUT",
        url: "https://www.digikala.com/seller/CGAUT/",
        rating: {
          total_rate: 78,
          total_count: 3293,
          commitment: 99.7,
          no_return: 99.4,
          on_time_shipping: 99.5,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 4.6,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "3 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 21800000,
        rrp_price: 36000000,
        order_limit: 2,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 39,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده و دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
          {
            title: "ارسال فروشنده",
            description:
              "این کالا در انبار فروشنده موجود و آماده پردازش است و امکان ارسال مستقیم توسط فروشنده دارد.",
            has_lead_time: false,
            type: "seller",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: true,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 2946963,
    title_fa: "دریل چکشی رونیکس مدل 2211",
    title_en: "Ronix 2211 impact drill",
    url: {
      uri: "/product/dkp-2946963/دریل-چکشی-رونیکس-مدل-2211",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "رونیکس",
      category: "[TC,ابزار برقی]",
      metric6: 2909,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 4.4,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سوراخکاری و پیچاندن",
      item_category5: "دریل",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
      is_jet_eligible: true,
      cash_back: 0,
      is_general_location_jet_eligible: false,
      fast_shipping_text: "ارسال امروز",
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/121735238.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/121735238.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 88,
      count: 2909,
    },
    default_variant: {
      id: 21162999,
      lead_time: 0,
      rank: 99.71,
      rate: 88.4,
      statistics: {
        totally_satisfied: {
          rate_count: 274,
          rate: 53.73,
        },
        satisfied: {
          rate_count: 198,
          rate: 38.82,
        },
        neutral: {
          rate_count: 21,
          rate: 4.12,
        },
        dissatisfied: {
          rate_count: 10,
          rate: 1.96,
        },
        totally_dissatisfied: {
          rate_count: 7,
          rate: 1.37,
        },
        total_count: 510,
        total_rate: 88.4,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: true,
      },
      digiplus: {
        services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
        is_jet_eligible: true,
        cash_back: 0,
        is_general_location_jet_eligible: false,
        fast_shipping_text: "ارسال امروز",
      },
      warranty: {
        id: 336,
        title_fa: "گارانتی 12 ماهه رونیکس",
        title_en: "گارانتی 12 ماهه رونیکس",
      },
      seller: {
        id: 1,
        title: "دیجی‌کالا",
        code: "5A52N",
        url: "https://www.digikala.com/seller/5A52N/",
        rating: {
          total_rate: 0,
          total_count: 0,
          commitment: 100,
          no_return: 99.9,
          on_time_shipping: 100,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 5,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "7 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 15530000,
        rrp_price: 15530000,
        order_limit: 30,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا",
            description:
              "این کالا در انبار دیجی‌کالا موجود و آماده پردازش است و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: false,
            type: "digikala",
          },
          {
            title: "ارسال امروز (فعلا در شهر تهران و کرج)",
            description:
              "اگر سفارش را قبل از ساعت ۶ عصر ثبت کنید، همان روز ارسال می‌شود. در صورت ثبت سفارش بعد از ساعت ۶ عصر، فردا ارسال خواهد شد.",
            has_lead_time: false,
            type: "jet",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 14000000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 9605475,
    title_fa: "مجموعه 27 عددی دریل پیچ گوشتی شارژی کبالت مدل CD12",
    title_en: "",
    url: {
      uri: "/product/dkp-9605475/مجموعه-27-عددی-دریل-پیچ-گوشتی-شارژی-کبالت-مدل-cd12",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,ابزار برقی]",
      metric6: 28,
      dimension2: 21,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 4.4,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سوراخکاری و پیچاندن",
      item_category5: "دریل",
    },
    product_type: "product",
    digiplus: {
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/68046c8bd4451a212aed939a1b6021d4e6d174f0_1665259179.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/68046c8bd4451a212aed939a1b6021d4e6d174f0_1665259179.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 88,
      count: 28,
    },
    default_variant: {
      id: 34450399,
      lead_time: 1,
      rank: 99.87,
      rate: 87.2,
      statistics: {
        totally_satisfied: {
          rate_count: 16,
          rate: 57.14,
        },
        satisfied: {
          rate_count: 10,
          rate: 35.71,
        },
        neutral: {
          rate_count: 0,
          rate: 0,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 2,
          rate: 7.14,
        },
        total_count: 28,
        total_rate: 87.2,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: true,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 272,
        title_fa: "گارانتی اصالت و سلامت فیزیکی کالا",
        title_en: "گارانتی اصالت و سلامت فیزیکی کالا",
      },
      seller: {
        id: 388896,
        title: "کامودیتی",
        code: "CGAUT",
        url: "https://www.digikala.com/seller/CGAUT/",
        rating: {
          total_rate: 78,
          total_count: 3293,
          commitment: 99.8,
          no_return: 99.4,
          on_time_shipping: 99.6,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 4.6,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "3 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 15880000,
        rrp_price: 20000000,
        order_limit: 2,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 21,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده و دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
          {
            title: "ارسال فروشنده",
            description:
              "این کالا در انبار فروشنده موجود و آماده پردازش است و امکان ارسال مستقیم توسط فروشنده دارد.",
            has_lead_time: false,
            type: "seller",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: true,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 7926490,
    title_fa: "مجموعه 34 عددی دریل پیچ گوشتی چکشی شارژی جاب مدل JBE-7721",
    title_en: "",
    url: {
      uri: "/product/dkp-7926490/مجموعه-34-عددی-دریل-پیچ-گوشتی-چکشی-شارژی-جاب-مدل-jbe-7721",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "جاب",
      category: "[TC,ابزار برقی]",
      metric6: 53,
      dimension2: 61,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 4.2,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سوراخکاری و پیچاندن",
      item_category5: "دریل",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/fad8cba9745076abfed01f4444c1207c90bf7f80_1645531694.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/fad8cba9745076abfed01f4444c1207c90bf7f80_1645531694.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 84,
      count: 53,
    },
    default_variant: {
      id: 27844583,
      lead_time: 1,
      rank: 99.85,
      rate: 85,
      statistics: {
        totally_satisfied: {
          rate_count: 23,
          rate: 44.23,
        },
        satisfied: {
          rate_count: 23,
          rate: 44.23,
        },
        neutral: {
          rate_count: 3,
          rate: 5.77,
        },
        dissatisfied: {
          rate_count: 2,
          rate: 3.85,
        },
        totally_dissatisfied: {
          rate_count: 1,
          rate: 1.92,
        },
        total_count: 52,
        total_rate: 85,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 63337,
        title: "کمپکس",
        code: "9NYRH",
        url: "https://www.digikala.com/seller/9NYRH/",
        rating: {
          total_rate: 78,
          total_count: 9401,
          commitment: 99.9,
          no_return: 99.2,
          on_time_shipping: 95.2,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.45,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "5 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 22300000,
        rrp_price: 57000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 61,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 22290000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 11768187,
    title_fa: "اینورتر جوشکاری 450 آمپر جاب مدل IGBT-450 X",
    title_en: "",
    url: {
      uri: "/product/dkp-11768187/اینورتر-جوشکاری-450-آمپر-جاب-مدل-igbt-450-x",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "جاب",
      category: "[TC,ابزار برقی]",
      metric6: 91,
      dimension2: 60,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 3.8,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار اتصال و جوش",
      item_category5: "دستگاه جوش",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/312f9b408746dc98a7e305189283d576f10aa0bb_1687613183.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/312f9b408746dc98a7e305189283d576f10aa0bb_1687613183.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 76,
      count: 91,
    },
    default_variant: {
      id: 41133629,
      lead_time: 1,
      rank: 95.25,
      rate: 75,
      statistics: {
        totally_satisfied: {
          rate_count: 20,
          rate: 27.4,
        },
        satisfied: {
          rate_count: 31,
          rate: 42.47,
        },
        neutral: {
          rate_count: 9,
          rate: 12.33,
        },
        dissatisfied: {
          rate_count: 10,
          rate: 13.7,
        },
        totally_dissatisfied: {
          rate_count: 3,
          rate: 4.11,
        },
        total_count: 73,
        total_rate: 75,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 6579,
        title_fa: "گارانتی 12 ماهه گروه صنعتی جاب",
        title_en: "گارانتی 12 ماهه گروه صنعتی جاب",
      },
      seller: {
        id: 63337,
        title: "کمپکس",
        code: "9NYRH",
        url: "https://www.digikala.com/seller/9NYRH/",
        rating: {
          total_rate: 78,
          total_count: 9404,
          commitment: 99.9,
          no_return: 99.2,
          on_time_shipping: 95.2,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.45,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "5 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 21990000,
        rrp_price: 55000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 60,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 21980000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 11245187,
    title_fa: "شلنگ کارواش ریمکس مدل YYS-491 به همراه آب پاش",
    title_en: "",
    url: {
      uri: "/product/dkp-11245187/شلنگ-ریمکس-مدل-yys-491-به-همراه-آب-پاش",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "ریمکس",
      category: "[TC,ابزار برقی]",
      metric6: 3,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 4.3,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "لوازم جانبی ابزار برقی، شارژی و بادی",
      item_category5: "لوازم جانبی کارواش",
    },
    product_type: "product",
    digiplus: {
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/2493ce40bb58aeac50bf3447b66fdef850d2b8a3_1683270805.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/2493ce40bb58aeac50bf3447b66fdef850d2b8a3_1683270805.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 86,
      count: 3,
    },
    default_variant: {
      id: 39909400,
      lead_time: 1,
      rank: 99.87,
      rate: 86.6,
      statistics: {
        totally_satisfied: {
          rate_count: 1,
          rate: 33.33,
        },
        satisfied: {
          rate_count: 2,
          rate: 66.67,
        },
        neutral: {
          rate_count: 0,
          rate: 0,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 3,
        total_rate: 86.6,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: true,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
        is_ship_by_seller_restricted: true,
      },
      digiplus: {
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 272,
        title_fa: "گارانتی اصالت و سلامت فیزیکی کالا",
        title_en: "گارانتی اصالت و سلامت فیزیکی کالا",
      },
      color: {
        id: 1,
        title: "مشکی",
        hex_code: "#212121",
      },
      seller: {
        id: 580386,
        title: "روتا",
        code: "D2K2Y",
        url: "https://www.digikala.com/seller/D2K2Y/",
        rating: {
          total_rate: 81,
          total_count: 2308,
          commitment: 99.7,
          no_return: 99.3,
          on_time_shipping: 99.1,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 4.2,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "2 سال و 9 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 24000000,
        rrp_price: 24000000,
        order_limit: 2,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده و دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
          {
            title: "ارسال فروشنده",
            description:
              "این کالا در انبار فروشنده موجود و آماده پردازش است و امکان ارسال مستقیم توسط فروشنده دارد.",
            has_lead_time: false,
            type: "seller",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: true,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 15580000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
    colors: [
      {
        id: 1,
        title: "مشکی",
        hex_code: "#212121",
      },
    ],
  },
  {
    id: 11529769,
    title_fa: "کارواش خودرو چجیبا مدل G200",
    title_en: "",
    url: {
      uri: "/product/dkp-11529769/کارواش-مدل-chejieba01",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,ابزار برقی]",
      metric6: 2,
      dimension2: 46,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 2,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "خودرو و موتورسیکلت",
      item_category3: "لوازم جانبی خودرو",
      item_category4: "نظافت و نگهداری خودرو",
      item_category5: "کارواش",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
      is_jet_eligible: true,
      cash_back: 0,
      is_general_location_jet_eligible: false,
      fast_shipping_text: "ارسال امروز",
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/f9ac33f3bed9185fb7add18ee825f69787d0d8ef_1685653912.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/f9ac33f3bed9185fb7add18ee825f69787d0d8ef_1685653912.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 40,
      count: 2,
    },
    default_variant: {
      id: 40578553,
      lead_time: 0,
      rank: 99.4,
      rate: 40,
      statistics: {
        totally_satisfied: {
          rate_count: 0,
          rate: 0,
        },
        satisfied: {
          rate_count: 0,
          rate: 0,
        },
        neutral: {
          rate_count: 1,
          rate: 50,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 1,
          rate: 50,
        },
        total_count: 2,
        total_rate: 40,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: true,
        is_ship_by_seller_restricted: false,
      },
      digiplus: {
        services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
        is_jet_eligible: true,
        cash_back: 0,
        is_general_location_jet_eligible: false,
        fast_shipping_text: "ارسال امروز",
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 141150,
        title: "مرسانا شاپینگ",
        code: "AFNYM",
        url: "https://www.digikala.com/seller/AFNYM/",
        rating: {
          total_rate: 76,
          total_count: 1397,
          commitment: 99.7,
          no_return: 98.7,
          on_time_shipping: 99.8,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.4,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "4 سال و 6 ماه",
      },
      digiclub: {
        point: 135,
      },
      price: {
        selling_price: 13500000,
        rrp_price: 25000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 46,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا",
            description:
              "این کالا در انبار دیجی‌کالا موجود و آماده پردازش است و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: false,
            type: "digikala",
          },
          {
            title: "ارسال امروز (فعلا در شهر تهران و کرج)",
            description:
              "اگر سفارش را قبل از ساعت ۶ عصر ثبت کنید، همان روز ارسال می‌شود. در صورت ثبت سفارش بعد از ساعت ۶ عصر، فردا ارسال خواهد شد.",
            has_lead_time: false,
            type: "jet",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 12366268,
    title_fa: "کمپرسور هوا اینتیمکث کد 1101 مجموعه 7 عددی",
    title_en: "",
    url: {
      uri: "/product/dkp-12366268/کمپرسور-هوا-اینتیمکث-کد-1101-مجموعه-7-عددی",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,ابزار برقی]",
      metric6: 17,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 4.3,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "خودرو و موتورسیکلت",
      item_category3: "لوازم جانبی خودرو",
      item_category4: "ابزار خودرو",
      item_category5: "کمپرسور هوا",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/e1769ef3a80d69e6426f3ff97d499eb7e4c8f119_1691908942.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/e1769ef3a80d69e6426f3ff97d499eb7e4c8f119_1691908942.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 86,
      count: 17,
    },
    default_variant: {
      id: 44514202,
      lead_time: 1,
      rank: 99.62,
      rate: 0,
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: true,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 998988,
        title: "ابزار فروشی اسدی",
        code: "EJ2NC",
        url: "https://www.digikala.com/seller/EJ2NC/",
        rating: {
          total_rate: 83,
          total_count: 7,
          commitment: 100,
          no_return: 100,
          on_time_shipping: 81.8,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.75,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "1 سال و 2 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 16939100,
        rrp_price: 16939100,
        order_limit: 3,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        marketable_stock: 3,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 12990000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 12715398,
    title_fa: "مجموعه 28 عددی دریل پیچ گوشتی شارژی دلیکس مدل 24V",
    title_en: "",
    url: {
      uri: "/product/dkp-12715398/مجموعه-28-عددی-دریل-شارژی-دلیکس-کد-24v",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,ابزار برقی]",
      metric6: 16,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 3.8,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سوراخکاری و پیچاندن",
      item_category5: "دریل",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/c276092186895519f039ab328015b3dad1db2fd6_1695244478.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/c276092186895519f039ab328015b3dad1db2fd6_1695244478.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 76,
      count: 16,
    },
    default_variant: {
      id: 44148029,
      lead_time: 1,
      rank: 99.75,
      rate: 0,
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 1020201,
        title: "بازرگانی مدیکس",
        code: "EMGWY",
        url: "https://www.digikala.com/seller/EMGWY/",
        rating: {
          total_rate: 0,
          total_count: 0,
          commitment: 100,
          no_return: 100,
          on_time_shipping: 100,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 5,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "1 سال و 1 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 40000000,
        rrp_price: 40000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 15980000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 12072356,
    title_fa: "اینورتر جوشکاری 400 آمپر جاب مدل IGBT-400 X",
    title_en: "",
    url: {
      uri: "/product/dkp-12072356/اینورتر-جوشکاری-400-آمپر-جاب-مدل-igbt-400-x",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "جاب",
      category: "[TC,ابزار برقی]",
      metric6: 16,
      dimension2: 55,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 4.3,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار اتصال و جوش",
      item_category5: "دستگاه جوش",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/75c29bc305bb80b76bed9624d3e5d7f5c8eb6879_1689578409.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/75c29bc305bb80b76bed9624d3e5d7f5c8eb6879_1689578409.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 86,
      count: 16,
    },
    default_variant: {
      id: 41810973,
      lead_time: 1,
      rank: 99.86,
      rate: 86.2,
      statistics: {
        totally_satisfied: {
          rate_count: 8,
          rate: 50,
        },
        satisfied: {
          rate_count: 6,
          rate: 37.5,
        },
        neutral: {
          rate_count: 1,
          rate: 6.25,
        },
        dissatisfied: {
          rate_count: 1,
          rate: 6.25,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 16,
        total_rate: 86.2,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 6579,
        title_fa: "گارانتی 12 ماهه گروه صنعتی جاب",
        title_en: "گارانتی 12 ماهه گروه صنعتی جاب",
      },
      seller: {
        id: 63337,
        title: "کمپکس",
        code: "9NYRH",
        url: "https://www.digikala.com/seller/9NYRH/",
        rating: {
          total_rate: 78,
          total_count: 9420,
          commitment: 99.9,
          no_return: 99.2,
          on_time_shipping: 95.2,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.45,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "5 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 24990000,
        rrp_price: 55100000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 55,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 23990000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 5428078,
    title_fa: "مجموعه 78 عددی دریل پیچ گوشتی شارژی متابو مدل BS 14.4 Set ",
    title_en: "",
    url: {
      uri: "/product/dkp-5428078/مجموعه-78-عددی-دریل-پیچ-گوشتی-شارژی-متابو-مدل-bs-144-set",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متابو",
      category: "[TC,ابزار برقی]",
      metric6: 11,
      dimension2: 9,
      dimension6: 0,
      dimension7: "special-offer",
      dimension9: 4.5,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار سوراخکاری و پیچاندن",
      item_category5: "پیچ گوشتی برقی و شارژی",
    },
    product_type: "product",
    digiplus: {
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/34b38953150b50fbb4e3f2d69e1a5d8cdbab2be4_1623403090.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/34b38953150b50fbb4e3f2d69e1a5d8cdbab2be4_1623403090.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 90,
      count: 11,
    },
    default_variant: {
      id: 17398517,
      lead_time: 2,
      rank: 99.92,
      rate: 92,
      statistics: {
        totally_satisfied: {
          rate_count: 3,
          rate: 60,
        },
        satisfied: {
          rate_count: 2,
          rate: 40,
        },
        neutral: {
          rate_count: 0,
          rate: 0,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 5,
        total_rate: 92,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: true,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
        is_ship_by_seller_restricted: true,
      },
      digiplus: {
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 536191,
        title: "پارسیان ابزار",
        code: "CVTS9",
        url: "https://www.digikala.com/seller/CVTS9/",
        rating: {
          total_rate: 83,
          total_count: 2545,
          commitment: 100,
          no_return: 100,
          on_time_shipping: 100,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 5,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "2 سال و 11 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 126000000,
        rrp_price: 139000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: true,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        marketable_stock: 1,
        discount_percent: 9,
        badge: {
          title: "فروش ویژه",
          color: "#E6123D",
        },
        is_digiplus_promotion: false,
        is_digiplus_early_access: false,
        is_application_incredible: false,
        is_lightening_deal: false,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال فروشنده از 1 روز کاری دیگر",
            description:
              "این کالا در انبار فروشنده موجود و آماده پردازش است و امکان ارسال مستقیم توسط فروشنده دارد.",
            has_lead_time: true,
            type: "seller",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: true,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
    badges: [
      {
        icon: {
          url: [
            "https://dkstatics-public.digikala.com/digikala-products/205e0f437b66674b8fc7daac42ac471f7531f114_1629723777.png",
          ],
        },
        title: "قابلیت تنظیم سرعت",
      },
    ],
  },
  {
    id: 2310219,
    title_fa: "کارواش آنووی ریوربری مدل HOT 2021N",
    title_en: "",
    url: {
      uri: "/product/dkp-2310219/کارواش-آنووی-ریوربری-مدل-hot-2021n",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "آنووی ریوربری",
      category: "[TC,ابزار برقی]",
      metric6: 0,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 0,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "خودرو و موتورسیکلت",
      item_category3: "لوازم جانبی خودرو",
      item_category4: "نظافت و نگهداری خودرو",
      item_category5: "کارواش",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/114897830.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/114897830.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 0,
      count: 0,
    },
    default_variant: {
      id: 38576401,
      lead_time: 2,
      rank: 99.84,
      rate: 0,
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 7267,
        title: "ابزار سنتر",
        code: "5AGC5",
        url: "https://www.digikala.com/seller/5AGC5/",
        rating: {
          total_rate: 84,
          total_count: 2877,
          commitment: 100,
          no_return: 99.3,
          on_time_shipping: 100,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 4.2,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "5 سال و 8 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 2040000000,
        rrp_price: 2040000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        marketable_stock: 1,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "باربری توسط دیجی‌کالا از 2 روز دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 8821217,
    title_fa: "دستگاه جوش تفنگی 400 آمپر باس مدل LIFE_STYLE_MMA_400",
    title_en: "",
    url: {
      uri: "/product/dkp-8821217/دستگاه-جوش-تفنگی-400-آمپر-باس-مدل-life-style-mma-400",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "باس",
      category: "[TC,ابزار برقی]",
      metric6: 44,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 3.8,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار اتصال و جوش",
      item_category5: "دستگاه جوش",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
      is_jet_eligible: true,
      cash_back: 0,
      is_general_location_jet_eligible: false,
      fast_shipping_text: "ارسال امروز",
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/7c40a1301bbcddffe3e861ae040efa3fe774a69b_1655888709.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/7c40a1301bbcddffe3e861ae040efa3fe774a69b_1655888709.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 76,
      count: 44,
    },
    default_variant: {
      id: 44303400,
      lead_time: 0,
      rank: 93.88,
      rate: 60,
      statistics: {
        totally_satisfied: {
          rate_count: 0,
          rate: 0,
        },
        satisfied: {
          rate_count: 0,
          rate: 0,
        },
        neutral: {
          rate_count: 1,
          rate: 100,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 1,
        total_rate: 60,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: true,
      },
      digiplus: {
        services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
        is_jet_eligible: true,
        cash_back: 0,
        is_general_location_jet_eligible: false,
        fast_shipping_text: "ارسال امروز",
      },
      warranty: {
        id: 272,
        title_fa: "گارانتی اصالت و سلامت فیزیکی کالا",
        title_en: "گارانتی اصالت و سلامت فیزیکی کالا",
      },
      seller: {
        id: 1104271,
        title: "تیوامارکت",
        code: "F29JH",
        url: "https://www.digikala.com/seller/F29JH/",
        rating: {
          total_rate: 87,
          total_count: 83,
          commitment: 99.5,
          no_return: 99.5,
          on_time_shipping: 99.6,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 4.6,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "7 ماه و 1 روز",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 28300000,
        rrp_price: 28300000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        marketable_stock: 1,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا",
            description:
              "این کالا در انبار دیجی‌کالا موجود و آماده پردازش است و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: false,
            type: "digikala",
          },
          {
            title: "ارسال امروز (فعلا در شهر تهران و کرج)",
            description:
              "اگر سفارش را قبل از ساعت ۶ عصر ثبت کنید، همان روز ارسال می‌شود. در صورت ثبت سفارش بعد از ساعت ۶ عصر، فردا ارسال خواهد شد.",
            has_lead_time: false,
            type: "jet",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 24000000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 11532468,
    title_fa: "جستجوگر  میدان مغناطیسی مدل لوپ  فلزیاب",
    title_en: "",
    url: {
      uri: "/product/dkp-11532468/جستجوگر-میدان-مغناطیسی-مدل-لوپ-فلزیاب",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,لوازم الکتریکی ساختمان]",
      metric6: 0,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 0,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "قطعات الکترونیکی",
      item_category5: "",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/586ae107aeed6373d363f21a15bd743727ec67bb_1685684302.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/586ae107aeed6373d363f21a15bd743727ec67bb_1685684302.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 0,
      count: 0,
    },
    default_variant: {
      id: 40973732,
      lead_time: 1,
      rank: 100,
      rate: 0,
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 3019,
        title: "فلزیاب زرشناسان",
        code: "5A9VF",
        url: "https://www.digikala.com/seller/5A9VF/",
        rating: {
          total_rate: 100,
          total_count: 1,
          commitment: 100,
          no_return: 100,
          on_time_shipping: 100,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 5,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "5 سال و 10 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 35000000,
        rrp_price: 35000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 11049629,
    title_fa: "کارواش باسئوس مدل GF8",
    title_en: "",
    url: {
      uri: "/product/dkp-11049629/کارواش-باسئوس-مدل-gf8",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "بیسوس",
      category: "[TC,ابزار برقی]",
      metric6: 1,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 1,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "خودرو و موتورسیکلت",
      item_category3: "لوازم جانبی خودرو",
      item_category4: "نظافت و نگهداری خودرو",
      item_category5: "کارواش",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
      is_jet_eligible: true,
      cash_back: 0,
      is_general_location_jet_eligible: false,
      fast_shipping_text: "ارسال امروز",
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/98bd6781b0b916b1a70a4f2f19f1992fac06e17d_1681209334.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/98bd6781b0b916b1a70a4f2f19f1992fac06e17d_1681209334.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 20,
      count: 1,
    },
    default_variant: {
      id: 39933148,
      lead_time: 0,
      rank: 99.2,
      rate: 20,
      statistics: {
        totally_satisfied: {
          rate_count: 0,
          rate: 0,
        },
        satisfied: {
          rate_count: 0,
          rate: 0,
        },
        neutral: {
          rate_count: 0,
          rate: 0,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 1,
          rate: 100,
        },
        total_count: 1,
        total_rate: 20,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: true,
        is_ship_by_seller_restricted: false,
      },
      digiplus: {
        services: ["ارسال رایگان", "ارسال فوری برای شهر تهران (رایگان)"],
        is_jet_eligible: true,
        cash_back: 0,
        is_general_location_jet_eligible: false,
        fast_shipping_text: "ارسال امروز",
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 317538,
        title: "فیدار نامدار سورین",
        code: "C62YF",
        url: "https://www.digikala.com/seller/C62YF/",
        rating: {
          total_rate: 83,
          total_count: 9409,
          commitment: 99.4,
          no_return: 98.9,
          on_time_shipping: 99.4,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.45,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "3 سال و 8 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 29000000,
        rrp_price: 29000000,
        order_limit: 3,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        marketable_stock: 3,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار دیجی‌کالا",
        has_lead_time: true,
        providers: [
          {
            title: "ارسال دیجی‌کالا",
            description:
              "این کالا در انبار دیجی‌کالا موجود و آماده پردازش است و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: false,
            type: "digikala",
          },
          {
            title: "ارسال امروز (فعلا در شهر تهران و کرج)",
            description:
              "اگر سفارش را قبل از ساعت ۶ عصر ثبت کنید، همان روز ارسال می‌شود. در صورت ثبت سفارش بعد از ساعت ۶ عصر، فردا ارسال خواهد شد.",
            has_lead_time: false,
            type: "jet",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 6807850,
    title_fa: "موتور برق پایونیر کد pi-1000x",
    title_en: "",
    url: {
      uri: "/product/dkp-6807850/موتور-برق-پایونیر-کد-pi-1000x",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,لوازم و ابزار باغبانی]",
      metric6: 20,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 3.6,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "تجهیزات صنعتی و انبارداری",
      item_category4: "موتور برق",
      item_category5: "",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/038b18edd91009dbe45727198e951bdd2973685a_1634711906.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/038b18edd91009dbe45727198e951bdd2973685a_1634711906.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 72,
      count: 20,
    },
    default_variant: {
      id: 43841938,
      lead_time: 1,
      rank: 99.79,
      rate: 0,
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
        is_ship_by_seller_restricted: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 3,
        title_fa: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
        title_en: "سرویس ویژه دیجی کالا: 7 روز تضمین بازگشت کالا",
      },
      seller: {
        id: 179444,
        title: "ابزارمن",
        code: "AMZTW",
        url: "https://www.digikala.com/seller/AMZTW/",
        rating: {
          total_rate: 79,
          total_count: 2800,
          commitment: 99.2,
          no_return: 98.8,
          on_time_shipping: 98.1,
        },
        properties: {
          is_trusted: false,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 3.2,
        grade: {
          label: "خیلی خوب",
          color: "#b1b64d",
        },
        registration_date: "4 سال و 3 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 64000000,
        rrp_price: 64000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        marketable_stock: 2,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 0,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
  {
    id: 10043695,
    title_fa: "هویه 30 وات مدل A++ بسته 20 عددی",
    title_en: "",
    url: {
      uri: "/product/dkp-10043695/هویه-30-وات-مدل-a-بسته-20-عددی",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "متفرقه",
      category: "[TC,ابزار برقی]",
      metric6: 6,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 4.3,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "ابزار برقی و شارژی",
      item_category4: "ابزار اتصال و جوش",
      item_category5: "هویه",
    },
    product_type: "product",
    digiplus: {
      services: ["ارسال رایگان"],
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/d4b520693cc62b521ddca78ee430b87def3dcea0_1671438276.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/d4b520693cc62b521ddca78ee430b87def3dcea0_1671438276.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 86,
      count: 6,
    },
    default_variant: {
      id: 36680437,
      lead_time: 1,
      rank: 99.87,
      rate: 86.6,
      statistics: {
        totally_satisfied: {
          rate_count: 3,
          rate: 50,
        },
        satisfied: {
          rate_count: 2,
          rate: 33.33,
        },
        neutral: {
          rate_count: 1,
          rate: 16.67,
        },
        dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        totally_dissatisfied: {
          rate_count: 0,
          rate: 0,
        },
        total_count: 6,
        total_rate: 86.6,
      },
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: false,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
      },
      digiplus: {
        services: ["ارسال رایگان"],
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 272,
        title_fa: "گارانتی اصالت و سلامت فیزیکی کالا",
        title_en: "گارانتی اصالت و سلامت فیزیکی کالا",
      },
      color: {
        id: 3,
        title: "قرمز",
        hex_code: "#f44336",
      },
      seller: {
        id: 945690,
        title: "خرازی سارتو",
        code: "EAUCM",
        url: "https://www.digikala.com/seller/EAUCM/",
        rating: {
          total_rate: 84,
          total_count: 604,
          commitment: 99.9,
          no_return: 99.7,
          on_time_shipping: 97.1,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 4.5,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "1 سال و 6 ماه",
      },
      digiclub: {
        point: 69,
      },
      price: {
        selling_price: 6898100,
        rrp_price: 6898100,
        order_limit: 30,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: true,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده",
        has_lead_time: false,
        providers: [
          {
            title: "ارسال دیجی‌کالا از 1 روز کاری دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: false,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 5970000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
    colors: [
      {
        id: 3,
        title: "قرمز",
        hex_code: "#f44336",
      },
    ],
  },
  {
    id: 8884238,
    title_fa: "موتور برق کامینز مدل ES68D5",
    title_en: "",
    url: {
      uri: "/product/dkp-8884238/موتور-برق-کامینز-مدل-es68d5",
    },
    status: "marketable",
    has_quick_view: false,
    data_layer: {
      brand: "کامینز",
      category: "[TC,لوازم و ابزار باغبانی]",
      metric6: 0,
      dimension2: 0,
      dimension6: 0,
      dimension7: "none",
      dimension9: 0,
      dimension11: 0,
      dimension20: "marketable",
      item_category2: "ابزار آلات و تجهیزات",
      item_category3: "تجهیزات صنعتی و انبارداری",
      item_category4: "موتور برق",
      item_category5: "",
    },
    product_type: "product",
    digiplus: {
      is_jet_eligible: false,
      cash_back: 0,
      is_general_location_jet_eligible: false,
    },
    images: {
      main: {
        url: [
          "https://dkstatics-public.digikala.com/digikala-products/621324e48ac7824c8c555ba74f5eff5c616f30b4_1657365441.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/quality,q_80",
        ],
        webp_url: [
          "https://dkstatics-public.digikala.com/digikala-products/621324e48ac7824c8c555ba74f5eff5c616f30b4_1657365441.jpg?x-oss-process=image/resize,m_lfit,h_300,w_300/format,webp/quality,q_80",
        ],
      },
    },
    rating: {
      rate: 0,
      count: 0,
    },
    default_variant: {
      id: 32447098,
      lead_time: 2,
      rank: 99.77,
      rate: 0,
      status: "marketable",
      properties: {
        is_fast_shipping: false,
        is_ship_by_seller: true,
        is_multi_warehouse: false,
        has_similar_variants: false,
        is_rural: false,
        in_digikala_warehouse: false,
        is_ship_by_seller_restricted: true,
      },
      digiplus: {
        is_jet_eligible: false,
        cash_back: 0,
        is_general_location_jet_eligible: false,
      },
      warranty: {
        id: 8874,
        title_fa: "گارانتی 12 ماهه اعلا نیرو",
        title_en: "گارانتی 12 ماهه اعلا نیرو",
      },
      seller: {
        id: 355134,
        title: "اعلا نیرو",
        code: "CC63F",
        url: "https://www.digikala.com/seller/CC63F/",
        rating: {
          total_rate: 77,
          total_count: 6,
          commitment: 100,
          no_return: 100,
          on_time_shipping: 100,
        },
        properties: {
          is_trusted: true,
          is_official: false,
          is_roosta: false,
          is_new: false,
        },
        stars: 5,
        grade: {
          label: "عالی",
          color: "#00a049",
        },
        registration_date: "3 سال و 6 ماه",
      },
      digiclub: {
        point: 150,
      },
      price: {
        selling_price: 6847000000,
        rrp_price: 6847000000,
        order_limit: 1,
        is_incredible: false,
        is_promotion: false,
        is_locked_for_digiplus: false,
        bnpl_active: false,
        discount_percent: 0,
        is_plus_early_access: false,
      },
      shipment_methods: {
        description: "موجود در انبار فروشنده و دیجی‌کالا",
        has_lead_time: false,
        providers: [
          {
            title: "باربری توسط دیجی‌کالا از 2 روز دیگر",
            description:
              "این کالا پس از مدت زمان مشخص شده توسط فروشنده در انبار دیجی‌کالا تامین و آماده پردازش می‌گردد و توسط پیک دیجی‌کالا در بازه انتخابی ارسال خواهد شد.",
            has_lead_time: true,
            type: "digikala",
          },
          {
            title: "ارسال فروشنده از 2 روز کاری دیگر",
            description:
              "این کالا در انبار فروشنده موجود و آماده پردازش است و امکان ارسال مستقیم توسط فروشنده دارد.",
            has_lead_time: true,
            type: "seller",
          },
        ],
      },
      has_importer_price: false,
      manufacture_price_not_exist: false,
      has_best_price_in_last_month: false,
    },
    properties: {
      is_fast_shipping: false,
      is_ship_by_seller: true,
      free_shipping_badge: false,
      is_multi_warehouse: false,
      is_fake: false,
      has_gift: false,
      min_price_in_last_month: 6282000000,
      is_non_inventory: false,
      is_ad: false,
      is_jet_eligible: false,
      is_medical_supplement: false,
    },
  },
];
